### ISSUE TITLE
OLED Blinds not working in Android 12

### ISSUE THREAD

**Issue by HernandezEduin** [catly1/OledSaver#1]
Hi,

I've been using OLED Blinds for about a year now (great job by the way), but after a recent android update, I'm no longer able to use it when I play FGO. It works if I'm using any other non-gamming apps, but whenever I try it on a game, it doesn't show on top of the app.

**Comment by catly1** [comment]
Hi, what phone do you have? My galaxy phone is also at android 12 and it is still working fine. Is it a pixel?

**Comment by HernandezEduin** [comment]
Oh really, I thought it was an Android 12 thing.

Mine is a ZenFone 7. The issue started with a recent update to Android 12 a month ago.

**Comment by catly1** [comment]
Hmm. So it just doesn't appear at all? Is the passthrough feature on? That
one doesn't work for Android 12 now. The app might be crashing so if it's
on then try turning it off. Also, do you have the latest release?

**Comment by HernandezEduin** [comment]
It doesn't appear at all while I'm in a game. The moment I switch to another app or the main screen, the overlay bars appear. When I go back to the game, they disappear.

I tried it for both passthrough on and off.

I'm using the current release from the playstore, which should be 5.3.

**Comment by HernandezEduin** [comment]
Here's a video on what's going on: 
[https://youtu.be/1FvtrDK5Zak](Video)

**Comment by catly1** [comment]
I'm thinking the bars might have just been saved out of bounds. It's rare
but can happen. Have you tried pressing reset on the app?

**Comment by HernandezEduin** [comment]
I tried it, but the issue still persists.

**Comment by catly1** [comment]
I can't reproduce it using a pixel 2 and a Galaxy Fold 3 phone. Can you go to the software information of your phone and give me a build number? I'll try to do some research on what Asus did for the update. Manufacturers like to put their own spin on things.

Do you have any other app by the way that can draw over other apps like OLED Blinds? Like Facebook messenger? See if those chat bubbles can appear on top of FGO.

**Comment by HernandezEduin** [comment]
Build number: WW_31.0210.0210.250

I tried using built-in apps that allow overlay (such as the calculator), but it seems like it does not allow it when playing.

**Comment by catly1** [comment]
There must be a built-in game mode or focus mode for that phone that prevents pop-ups. Maybe try turning that off. And sorry for the late reply, I was at an Anime convention hah.

**Comment by HernandezEduin** [comment]
Thanks, I'll see if can modify that feature. I just need oled blinds so I can read the story and enjoy the art without getting distracted by blue bars on the side.

How was it? Was it Anime Expo 2022?

**Comment by catly1** [comment]
Yes, it was Anime Expo. It was a bit more manageable this time around because there weren't a lot of panels to go to. I got to the FGO panel and got included in that group picture the dev team took hah.

But I hope you can find a setting that can make this work.

**Comment by HernandezEduin** [comment]
Hi, I think I figured it out. I had to disable the game genie since that was disabling pop-ups.
